/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.visualizar;

import controle.ControleSistema;
import java.util.ArrayList;
import modelo.Chave;
import modelo.RelacaoGrupoPessoa;
import modelo.Pessoa;

/**
 *
 * @author italo
 */
public class JInternalFrameVisualizar extends javax.swing.JInternalFrame {

    private final ControleSistema controleSistema;

    /**
     * Creates new form JInternalFrameVisualizar
     * @param controleSistema
     */
    public JInternalFrameVisualizar(ControleSistema controleSistema) {
        initComponents();
        this.controleSistema = controleSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object o = controleSistema.getControleChave().searchAll(Pessoa.class);
        int n = 0;
        for (Pessoa p : (ArrayList<Pessoa>) o) {
            System.out.println("-------------------- Pessoa " + (n++) + " --------------------");
            System.out.println("Nome: " + p.getNome() + " Codigo: " + p.getCodigo() + " Barras: " + p.getCodigoDeBarras());
        }

        o = controleSistema.getControleChave().searchAll(Chave.class);
        n = 0;
        for (Chave p : (ArrayList<Chave>) o) {
            System.out.println("-------------------- Chave " + (n++) + " --------------------");
            System.out.println("Nome: " + p.getNome() + " Barras: " + p.getCodigoDeBarras());
        }

        o = controleSistema.getControleChave().searchAll(RelacaoGrupoPessoa.class);
        n = 0;
        int asd = 0;
        int sad = 0;
        for (RelacaoGrupoPessoa g : (ArrayList<RelacaoGrupoPessoa>) o) {
            System.out.println("------------------------------------------------------------");
            System.out.println("------------------------------------------------------------");
            System.out.println("-------------------- GrupoPessoa " + (n++) + " --------------------");
            /*System.out.println("Nome: " + g.getNome());

            for (Chave c : g.getListaChavePermitida()) {
                System.out.println("-------------------- Chave " + (asd++) + " --------------------");
                System.out.println("Nome: " + c.getNome() + " Barras: " + c.getCodigoDeBarras());
            }

            for (Pessoa p : (ArrayList<Pessoa>) g.getListaPessoaAcessoPermitido()) {
                System.out.println("-------------------- Pessoa " + (sad++) + " --------------------");
                System.out.println("Nome: " + p.getNome() + " Codigo: " + p.getCodigo() + " Barras: " + p.getCodigoDeBarras());
            }*/
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
