/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.grupo;

import controle.ControleSistema;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.RelacaoGrupoPessoa;

/**
 *
 * @author italo
 */
public class NovoJFrame extends javax.swing.JFrame {

    private ControleSistema controleSistema;
    ArrayList alPessoaDisponivel, alPessoaSelecionado, alChaveDisponivel, alChaveSelecionada;
    RelacaoGrupoPessoa grupoPessoa;
    
    /**
     * Creates new form NovoJFrame
     */
    public NovoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfNumeroMaximoDeChave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlPessoasDisponiveis = new javax.swing.JList();
        jToolBar3 = new javax.swing.JToolBar();
        jlbAdd12 = new javax.swing.JLabel();
        jlbAdd21 = new javax.swing.JLabel();
        jlbAddAll12 = new javax.swing.JLabel();
        jlbAddAll21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlPessoasSelecionadas = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlChavesDisponiveis = new javax.swing.JList();
        jToolBar4 = new javax.swing.JToolBar();
        jlbAdd34 = new javax.swing.JLabel();
        jlbAdd43 = new javax.swing.JLabel();
        jlbAddAll34 = new javax.swing.JLabel();
        jlbAddAll43 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlChavesSelecionadas = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jtfNumeroMaximoDeChave.setToolTipText("Quantidade máxima  de chaves que cada membro deste grupo poderá pegar");

        jLabel2.setText("Limite máximo de chaves:");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNumeroMaximoDeChave, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jtfNome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNumeroMaximoDeChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Grupo", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlPessoasDisponiveis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pessoas disponíveis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N
        jlPessoasDisponiveis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jlPessoasDisponiveis);

        jToolBar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar3.setRollover(true);

        jlbAdd12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbAdd12.setText(">");
        jlbAdd12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAdd12MouseClicked(evt);
            }
        });
        jToolBar3.add(jlbAdd12);

        jlbAdd21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbAdd21.setText("<");
        jlbAdd21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAdd21MouseClicked(evt);
            }
        });
        jToolBar3.add(jlbAdd21);

        jlbAddAll12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbAddAll12.setText(">>");
        jlbAddAll12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAddAll12MouseClicked(evt);
            }
        });
        jToolBar3.add(jlbAddAll12);

        jlbAddAll21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbAddAll21.setText("<<");
        jlbAddAll21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAddAll21MouseClicked(evt);
            }
        });
        jToolBar3.add(jlbAddAll21);

        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlPessoasSelecionadas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pessoas selecionados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlPessoasSelecionadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jlPessoasSelecionadas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pessoa", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlChavesDisponiveis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chaves disponíveis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 11))); // NOI18N
        jlChavesDisponiveis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(jlChavesDisponiveis);

        jToolBar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar4.setRollover(true);

        jlbAdd34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbAdd34.setText(">");
        jlbAdd34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAdd34MouseClicked(evt);
            }
        });
        jToolBar4.add(jlbAdd34);

        jlbAdd43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbAdd43.setText("<");
        jlbAdd43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAdd43MouseClicked(evt);
            }
        });
        jToolBar4.add(jlbAdd43);

        jlbAddAll34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbAddAll34.setText(">>");
        jlbAddAll34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAddAll34MouseClicked(evt);
            }
        });
        jToolBar4.add(jlbAddAll34);

        jlbAddAll43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbAddAll43.setText("<<");
        jlbAddAll43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAddAll43MouseClicked(evt);
            }
        });
        jToolBar4.add(jlbAddAll43);

        jScrollPane5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlChavesSelecionadas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chaves selecionados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jlChavesSelecionadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(jlChavesSelecionadas);

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Acesso do grupo às chaves:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(154, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Acesso", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbAdd12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAdd12MouseClicked
        // TODO add your handling code here:
        if (jlbAdd12.isEnabled()) {
            if (jlPessoasDisponiveis.isSelectionEmpty()) {
                JOptionPane.showMessageDialog(this, "Não há item selecionado na lista 1!");
            } else {
                alPessoaSelecionado.add(alPessoaDisponivel.get(jlPessoasDisponiveis.getSelectedIndex()));
                alPessoaDisponivel.remove(jlPessoasDisponiveis.getSelectedIndex());
                jlPessoasSelecionadas.setModel(controleSistema.setDefaultListModel(alPessoaSelecionado));
                jlPessoasDisponiveis.setModel(controleSistema.setDefaultListModel(alPessoaDisponivel));
            }
        }
    }//GEN-LAST:event_jlbAdd12MouseClicked

    private void jlbAdd21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAdd21MouseClicked
        // TODO add your handling code here:
        if (jlPessoasSelecionadas.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "Não há item selecionado na lista 2!");
        } else {
            alPessoaDisponivel.add(alPessoaSelecionado.get(jlPessoasSelecionadas.getSelectedIndex()));
            alPessoaSelecionado.remove(jlPessoasSelecionadas.getSelectedIndex());
            jlPessoasDisponiveis.setModel(controleSistema.setDefaultListModel(alPessoaDisponivel));
            jlPessoasSelecionadas.setModel(controleSistema.setDefaultListModel(alPessoaSelecionado));
        }
    }//GEN-LAST:event_jlbAdd21MouseClicked

    private void jlbAddAll12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAddAll12MouseClicked
        // TODO add your handling code here:
        alPessoaSelecionado.addAll(alPessoaDisponivel);
        alPessoaDisponivel.clear();
        jlPessoasSelecionadas.setModel(controleSistema.setDefaultListModel(alPessoaSelecionado));
        jlPessoasDisponiveis.setModel(controleSistema.setDefaultListModel(alPessoaDisponivel));
    }//GEN-LAST:event_jlbAddAll12MouseClicked

    private void jlbAddAll21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAddAll21MouseClicked
        // TODO add your handling code here:
        alPessoaDisponivel.addAll(alPessoaSelecionado);
        alPessoaSelecionado.clear();
        jlPessoasDisponiveis.setModel(controleSistema.setDefaultListModel(alPessoaDisponivel));
        jlPessoasSelecionadas.setModel(controleSistema.setDefaultListModel(alPessoaSelecionado));
    }//GEN-LAST:event_jlbAddAll21MouseClicked

    private void jlbAdd34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAdd34MouseClicked
        // TODO add your handling code here:
        if (jlbAdd34.isEnabled()) {
            if (jlChavesDisponiveis.isSelectionEmpty()) {
                JOptionPane.showMessageDialog(this, "Não há item selecionado na lista 1!");
            } else {
                alChaveDisponivel.add(alPessoaDisponivel.get(jlChavesDisponiveis.getSelectedIndex()));
                alChaveDisponivel.remove(jlChavesDisponiveis.getSelectedIndex());
                jlPessoasSelecionadas.setModel(controleSistema.setDefaultListModel(alChaveSelecionada));
                jlChavesDisponiveis.setModel(controleSistema.setDefaultListModel(alChaveDisponivel));
            }
        }
    }//GEN-LAST:event_jlbAdd34MouseClicked

    private void jlbAdd43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAdd43MouseClicked
        // TODO add your handling code here:
        if (jlChavesSelecionadas.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "Não há item selecionado na lista 2!");
        } else {
            alChaveDisponivel.add(alChaveSelecionada.get(jlChavesSelecionadas.getSelectedIndex()));
            alChaveSelecionada.remove(jlChavesSelecionadas.getSelectedIndex());
            jlChavesDisponiveis.setModel(controleSistema.setDefaultListModel(alChaveDisponivel));
            jlChavesSelecionadas.setModel(controleSistema.setDefaultListModel(alChaveSelecionada));
        }
    }//GEN-LAST:event_jlbAdd43MouseClicked

    private void jlbAddAll34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAddAll34MouseClicked
        // TODO add your handling code here:
        alChaveSelecionada.addAll(alChaveDisponivel);
        alChaveDisponivel.clear();
        jlChavesSelecionadas.setModel(controleSistema.setDefaultListModel(alChaveSelecionada));
        jlChavesDisponiveis.setModel(controleSistema.setDefaultListModel(alChaveDisponivel));
    }//GEN-LAST:event_jlbAddAll34MouseClicked

    private void jlbAddAll43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAddAll43MouseClicked
        // TODO add your handling code here:
        alChaveDisponivel.addAll(alChaveSelecionada);
        alChaveSelecionada.clear();
        jlChavesDisponiveis.setModel(controleSistema.setDefaultListModel(alChaveDisponivel));
        jlChavesSelecionadas.setModel(controleSistema.setDefaultListModel(alChaveSelecionada));
    }//GEN-LAST:event_jlbAddAll43MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JList jlChavesDisponiveis;
    private javax.swing.JList jlChavesSelecionadas;
    private javax.swing.JList jlPessoasDisponiveis;
    private javax.swing.JList jlPessoasSelecionadas;
    private javax.swing.JLabel jlbAdd12;
    private javax.swing.JLabel jlbAdd21;
    private javax.swing.JLabel jlbAdd34;
    private javax.swing.JLabel jlbAdd43;
    private javax.swing.JLabel jlbAddAll12;
    private javax.swing.JLabel jlbAddAll21;
    private javax.swing.JLabel jlbAddAll34;
    private javax.swing.JLabel jlbAddAll43;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumeroMaximoDeChave;
    // End of variables declaration//GEN-END:variables
}
